version: '3.9'

services:
  # Mongo DB
  mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    command: --replSet rs0
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/admin --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  mongo-init:
    image: mongo:4.0
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: mongo --host mongodb:27017 --eval rs.initiate()

  # Mongo Express
  mongo-express:
    image: mongo-express
    ports:
      - "80:8081"
    links:
      - mongodb:mongo
    depends_on:
      - mongodb
    restart: always
    command: ["node", "app"]

volumes:
  mongo_data:

