package com.livadoo.utils.security.domain

enum class Role {
    ROLE_SYSTEM_ADMINISTRATOR,
    SYSTEM_ACCOUNT,
}

const val ROLE_ANONYMOUS = "ROLE_ANONYMOUS"
const val ROLE_ADMIN = "ROLE_ADMIN"
const val ROLE_SUPER_ADMIN = "ROLE_SUPER_ADMIN"
const val ROLE_EDITOR = "ROLE_EDITOR"
const val ROLE_CUSTOMER = "ROLE_CUSTOMER"

const val SYSTEM_ACCOUNT = "system"

val STAFF_ROLES = listOf(ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_EDITOR)
val ADMIN_ROLES = listOf(ROLE_SUPER_ADMIN, ROLE_ADMIN)
