application:
  security:
    jwt:
      secret:
      token-validity-in-seconds:
      refresh-secret:
      refresh-token-validity-in-seconds:
  password-reset-key:
    validity-time-in-hours:

spring:
  data:
    mongodb:
      database: livadoo_db_dev
      uri: mongodb://localhost:27017/
      auto-index-creation: true
  web:
    resources:
      add-mappings: false


server:
  port: 9000
  servlet:
    encoding:
      force: true

logging:
  level:
    com.livadoo.services: DEBUG

livadoo:
  storage:
    google-cloud:
      public-bucket: bucket-name
      old-bucket: bucket-name
      new-bucket: bucket-name
      patch-bucket: false

error:
  handling:
    exception-logging: message_only
    http-statuses:
      java:
        lang:
          RuntimeException: bad_request
    search-super-class-hierarchy: true

