name: Build fat Jar
run-name: Run unit and integration tests from ${{ github.actor }} PR
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build app and run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -PlivadooDockerRegistrySnapshotsUrl=N/A
            -PlivadooDockerRegistryReleasesUrl=N/A
            -PlivadooDockerRegistryUsername=${{ vars.DOCKER_REGISTRY_SERVER_USERNAME }}
            -PlivadooDockerRegistryPassword=${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}
            -PbuildVersionNumber=${{ github.run_number }}
            -Porg.gradle.parallel=true
            -PdatasourceUrl=N/A
            -PdatabaseUserName=N/A
            -PdatabasePassword=N/A
            -PappProfile=dev